name: Build Docker image, generate & attach SBOM
description: |
  Build and push a multi-platform (always AMD64, configurably ARM64) Docker
  image and generate and attach an SBOM for all configured platforms.

inputs:
  build-arm:
    description: Whether or not to build the arm image
    required: true
  dockerfile:
    description: Dockerfile that describes the image
    required: true
  docker-args:
    description: Arguments to pass to the docker build-process
  images:
    description: The name(s) of the image(s) to load metadata for
    required: true
  language:
    description: The language and version that is included in this image
    required: true
  latest:
    description: Tag this image as 'latest' on top of the given tags
    required: true
  main-tag:
    description: The tag to attach the SBOMs to, defaults to the first tag returned from the metadata extraction
  signing-key:
    description: The key to use for signing the SBOM, base64 encoded
    required: true
  tags:
    description: All tags to set for this image, defaults to all tags returned from the metadata extraction
  target:
    description: Which stage in the Dockerfile to build
    required: true

runs:
  using: composite
  steps:
    - name: Extract metadata (tags, labels) for Docker image
      id: metadata
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      with:
        flavor: latest=${{ inputs.latest }}
        images: ${{ inputs.images }}
        labels: |
          org.opencontainers.image.authors=Team AppThreat <cloud@appthreat.com>
          org.opencontainers.image.vendor=CycloneDX
          ${{ inputs.main-tag && format('org.opencontainers.docker.cmd=docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t {0} -r /app --server', inputs.main-tag) || '' }}
          ${{ inputs.main-tag && inputs.language == 'rolling' && 'org.opencontainers.image.description=Rolling image with cdxgen SBOM generator based on tumbleweed'
           || inputs.main-tag && format('org.opencontainers.image.description=Image with cdxgen SBOM generator for {0} apps', inputs.language)
           || ''
          }}
    - name: Build and push image
      uses: ./.github/actions/build-docker-image
      with:
        dockerfile: ${{ inputs.dockerfile }}
        docker-args: ${{ inputs.docker-args }}
        labels: ${{ steps.metadata.outputs.labels }}
        output: type=registry
        platforms: linux/amd64${{ inputs.build-arm == 'true' && ',linux/arm64' || '' }}
        tags: ${{ inputs.tags || steps.metadata.outputs.tags }}
        target: ${{ inputs.target }}
    - name: Generate and attach SBOM for amd64
      uses: ./.github/actions/generate-attach-sbom
      with:
        dockerfile: ${{ inputs.dockerfile }}
        docker-args: ${{ inputs.docker-args }}
        platform: linux/amd64
        signing-key: ${{ inputs.signing-key }}
        tag: ${{ inputs.main-tag || fromJSON(steps.metadata.outputs.json).tags[0] }}
        target: ${{ inputs.target }}
    - name: Generate and attach SBOM for arm64
      if: ${{ inputs.build-arm == 'true' }}
      uses: ./.github/actions/generate-attach-sbom
      with:
        dockerfile: ${{ inputs.dockerfile }}
        docker-args: ${{ inputs.docker-args }}
        platform: linux/arm64
        signing-key: ${{ inputs.signing-key }}
        tag: ${{ inputs.main-tag || fromJSON(steps.metadata.outputs.json).tags[0] }}
        target: ${{ inputs.target }}
