# image statement
FROM hello-world

# image statement with build stage name
FROM hello-world AS HELLO

# reusing previous build stage as new stage
FROM HELLO AS WORLD

# Commented out image statement
# FROM hello-world
