FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine

ENV PATH=${PATH}:/usr/local/bin:

RUN apk update && apk add --no-cache \
    nodejs \
    npm \
    && npm install -g corepack \
    && node -v \
    && npm -v \
    && rm -rf /var/cache/apk/*
