FROM golang:1.24-alpine

ENV PATH=${PATH}:/usr/local/bin:

RUN apk update && apk add --no-cache \
    nodejs \
    npm \
    && npm install -g corepack \
    && node -v \
    && npm -v \
    && rm -rf /var/cache/apk/*

CMD ["/bin/bash"]
