blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/CycloneDX/cdxgen/discussions
    about: Please ask and answer questions here.
  - name: Specification Discussions
    url: https://github.com/CycloneDX/specification/discussions
    about: Questions and comments about the CycloneDX specification here.
  - name: Community slack support
    url: https://cyclonedx.slack.com/archives/C04NFFE1962
    about: Community slack channel.
  - name: Community slack invite
    url: https://cyclonedx.org/slack/invite
    about: Community slack invite.
