// Swift entity kinds
// https://github.com/swiftlang/swift/blob/main/tools/SourceKit/docs/SwiftSupport.txt
const SWIFT_ENTITY_KINDS = {
  IMPORT_CLANG: "source.lang.swift.import.module.clang",
  IMPORT_SWIFT: "source.lang.swift.import.module.swift",
  IMPORT_SOURCE: "source.lang.swift.import.sourcefile",
  DECL_EXTN_STRUCT: "source.lang.swift.decl.extension.struct",
  DECL_EXTN_CLASS: "source.lang.swift.decl.extension.class",
  DECL_EXTN_ENUM: "source.lang.swift.decl.extension.enum",
  DECL_FREE: "source.lang.swift.decl.function.free",
  REF_FREE: "source.lang.swift.ref.function.free",
  DECL_METHOD_INSTANCE: "source.lang.swift.decl.function.method.instance",
  REF_METHOD_INSTANCE: "source.lang.swift.ref.function.method.instance",
  DECL_METHOD_STATIC: "source.lang.swift.decl.function.method.static",
  REF_METHOD_STATIC: "source.lang.swift.ref.function.method.static",
  DECL_CONSTRUCTOR: "source.lang.swift.decl.function.constructor",
  REF_CONSTRUCTOR: "source.lang.swift.ref.function.constructor",
  DECL_DESTRUCTOR: "source.lang.swift.decl.function.destructor",
  REF_DESTRUCTOR: "source.lang.swift.ref.function.destructor",
  DECL_OPERATOR: "source.lang.swift.decl.function.operator",
  REF_OPERATOR: "source.lang.swift.ref.function.operator",
  DECL_SUBSCRIPT: "source.lang.swift.decl.function.subscript",
  REF_SUBSCRIPT: "source.lang.swift.ref.function.subscript",
  DECL_GETTER: "source.lang.swift.decl.function.accessor.getter",
  REF_GETTER: "source.lang.swift.ref.function.accessor.getter",
  DECL_SETTER: "source.lang.swift.decl.function.accessor.setter",
  REF_SETTER: "source.lang.swift.ref.function.accessor.setter",
  DECL_CLASS: "source.lang.swift.decl.class",
  REF_CLASS: "source.lang.swift.ref.class",
  DECL_STRUCT: "source.lang.swift.decl.struct",
  REF_STRUCT: "source.lang.swift.ref.struct",
  DECL_ENUM: "source.lang.swift.decl.enum",
  REF_ENUM: "source.lang.swift.ref.enum",
  DECL_ENUM_ELEMENT: "source.lang.swift.decl.enumelement",
  REF_ENUM_ELEMENT: "source.lang.swift.ref.enumelement",
  DECL_PROTOCOL: "source.lang.swift.decl.protocol",
  REF_PROTOCOL: "source.lang.swift.ref.protocol",
  DECL_TYPE_ALIAS: "source.lang.swift.decl.typealias",
  REF_TYPE_ALIAS: "source.lang.swift.ref.typealias",
  DECL_VAR_GLOBAL: "source.lang.swift.decl.var.global",
  REF_VAR_GLOBAL: "source.lang.swift.ref.var.global",
  DECL_VAR_INSTANCE: "source.lang.swift.decl.var.instance",
  REF_VAR_INSTANCE: "source.lang.swift.ref.var.instance",
  DECL_VAR_STATIC: "source.lang.swift.decl.var.static",
  REF_VAR_STATIC: "source.lang.swift.ref.var.static",
  DECL_VAR_LOCAL: "source.lang.swift.decl.var.local",
  REF_VAR_LOCAL: "source.lang.swift.ref.var.local",
};
for (const key of Object.keys(SWIFT_ENTITY_KINDS)) {
  if (key.toUpperCase() === key) {
    SWIFT_ENTITY_KINDS[SWIFT_ENTITY_KINDS[key]] = key;
  }
}
