name: AppImage

on: [workflow_dispatch]

jobs:
  build:
    if: github.repository == 'CycloneDX/cdxgen'
    # use ubuntu-20.04 due to avoid glic errors
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3.8 python3.8-dev python3-pip python3-testresources python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev
        # Install appimagetool AppImage
        sudo wget https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
        sudo chmod +x /usr/local/bin/appimagetool
        sudo pip3 install appimage-builder==0.8.1
        mkdir -p appimage-builder-cache
        wget https://github.com/AppImage/AppImageKit/releases/download/12/runtime-x86_64 -O appimage-builder-cache/runtime-x86_64
    - name: Build AppImage
      run: |
        appimage-builder --recipe appimage-builder.yml --skip-test
      env:
        UPDATE_INFO: gh-releases-zsync|cyclonedx|cdxgen|latest|*x86_64.AppImage.zsync
    - uses: actions/upload-artifact@v4
      with:
        name: AppImage
        path: './*.AppImage*'
