name: Build rolling image

# This workflow builds a fresh image for the current 'master'-branch every day
# and on pushes.
#
# Similar to `build-images`, this workflow only defines the image and building
# is handled in `image-build.yml`.
#
# The definition is the same as in `build-images.yml`, except for the fact it
# must be defined in a JSON-String, since parameters can only be transferred as
# simple types!

on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'contrib/**'
      - '*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  image:
    if: github.repository == 'CycloneDX/cdxgen'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
    with:
      image: |
        {
          "lang": "rolling",
          "distro": "opensuse",
          "base-image": {
            "lang": "lang"
          }
        }
