name: Build images

on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  images:
    if: github.repository == 'CycloneDX/cdxgen'
    strategy:
      fail-fast: true
      matrix:
        image:

#          - lang: dotnet6
#            fix-qemu: true
#            skip-arm: true
#            base-image:
#              additional-image: bci-dotnet
#            cdxgen-image:
#              additional-image: cdxgen-dotnet

          - lang: dotnet6
            distro: debian

          - lang: dotnet7
            skip-arm: true

          - lang: dotnet8
            skip-arm: true

          - lang: dotnet8
            distro: debian

          - lang: dotnet9
            skip-arm: true

          - lang: dotnet9
            distro: debian

          - lang: java8
            distro: temurin

          - lang: java11
            base-image:
              additional-image: java11-slim
            cdxgen-image:
              additional-image: cdxgen-java
              additional-image2: cdxgen-java11-slim
              additional-image3: cdxgen-java-slim

          - lang: java17

          - lang: java17-slim

          - lang: java21
            distro: temurin

          - lang: node20
            cdxgen-image:
              additional-image: cdxgen-node

          - lang: python36

          - lang: python39
            distro: opensuse

          - lang: python310
            distro: opensuse

          - lang: python311

          - lang: python312
            base-image:
              lang: lang
            cdxgen-image:
              additional-image: cdxgen-python

          - lang: ruby25
            fix-qemu: true
            skip-arm: true
            base-image:
              name: sle

          - lang: ruby26
            distro: debian
            runner: macos-hosted
            skip-arm: true

          - lang: ruby33
            distro: debian
            runner: macos-hosted

          - lang: ruby34
            distro: debian
            runner: macos-hosted

          - lang: swift6
            distro: debian
            runner: macos-hosted
            base-image:
              additional-image: debian-swift
            cdxgen-image:
              additional-image: cdxgen-debian-swift

          - lang: rolling
            distro: opensuse
            base-image:
              lang: lang
            cdxgen-image:
              skip-tags: true

    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/image-build.yml
    with:
      image: ${{ toJSON(matrix.image) }}
      runner: ${{ matrix.image.runner }}
