name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cdxgen:${{ github.sha }}
            ghcr.io/${{ github.repository }}/cdxgen:latest
  cdxgen:
    runs-on: ubuntu-latest
    name: Generate license information and upload it
    needs: push_to_registry
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - name: Generate license information and upload it
        id: cdxgen
        uses: sorenmat/cdxgen-action@main
        with:
          server-url: 'http://localhost/api/v1/bom'
          fetch-licenses: true
          token: '1234'            