name: test
on:
  pull_request_target: # Use pull_request_target
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          echo "I MODIFIED THE PIPELINE"
          cat .npmignore
        env:
          EVENT: ${{toJSON(github)}}
