name: test
on:
  pull_request_target: # Use pull_request_target
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
